### ISSUE TITLE
rock-roboviz: Crashes when loading a SDF model

### ISSUE THREAD

**Issue by caioaamaral** [rock-gui/gui-robot_model#31]
When trying to load a model uri, `rock-roboviz` crashes with the message "unknow mode sdfbundle"

```console
$ $(which rock-roboviz) "model://ur10"
[DEPRECATED] utilrb/hash/slice is deprecated, use backports' backports/2.5.0/hash/slice instead or the built-in method in Ruby >= 2.5
WARN: integrating typelib plugin using the TYPELIB_RUBY_PLUGIN_PATH environment variable is deprecated
WARN: just put a file called typelib_plugin.rb into a subfolder from the RUBYLIB (e.g. base/typelib_plugin.rb)
WARN: offending dir: /home/caioaamaral/workspaces/tutorial/install/share/typelib/ruby
Bundles[INFO]: Active bundles: hello_world
OroGen[WARN]: subclasses is deprecated: in cart_ctrl_wdls: use task_context "Name", subclasses: "Parent" do .. end instead
terminate called after throwing an instance of 'std::invalid_argument'
  what():  unknown mode sdfbundle
Aborted (core dumped)

```

**Comment by caioaamaral** [comment]
the following diff seems to fix the crash

```diff
diff --git a/bin/rock-roboviz b/bin/rock-roboviz
index 5c87431..dea7072 100755
--- a/bin/rock-roboviz
+++ b/bin/rock-roboviz
@@ -225,6 +225,7 @@ end
 if model_file_mode == 'sdfbundle'
     sdf_string = SDF.to_xml(SDF::Root.load(model_file).each_model.first)
     vis_gui.loadFromString(sdf_string.dup, 'sdf')
+    model_file_mode = 'sdf'
     if ctrl_gui
         ctrl_gui.initFromString(sdf_string.dup, model_file_mode.dup)
     end
```

But still, I couldn't send any joint command for the use case described on [this rock tutorial](https://www.rock-robotics.org/rock-and-syskit/basics/devices.html)

**Comment by maltewi** [comment]
Thanks @caioaamaral for reporting the bug. 
Your fix looks reasonable. ControlUI does not know a case for "sdfbundle" (cf. https://github.com/rock-gui/gui-control_ui/blob/891c356b2de5454ee51f8674702ca5780ee6083a/src/ControlUi.cc#L86).

Still I'd prefer to change `ctrl_gui.initFromString(sdf_string.dup, model_file_mode.dup)` into `ctrl_gui.initFromString(sdf_string.dup, 'sdf')` instead.
A pull request would be welcome.

Regarding the the problem of sending joint commands:
You should have to specify the ports that shold receive the joint commands with the `-c` option.
E.g.:
```
rock-roboviz with the -s my_task:port_with_joint_state_samples -c my_possible_different_task:port_that_receives_joint_commands --sdf my_sdf_file.sdf
```

Then to send commands, make sure to uncheck "Update joint state" (and possible check "Keep sending commands" if you want send commands directly when changing the sliders)

If this does not help, please be more specific in describing the problem.
