### ISSUE TITLE
Fails to build on debian testing

### ISSUE THREAD

**Issue by planthaber** [rock-gui/gui-robot_model#4]
Commit https://github.com/rock-gui/gui-robot_model/commit/a9b659c9d047cc2743b55cd117dc3d158441578b is using qt's "moc", but it is not found.

I think this is because the find qt stuff is commented at the beginning of https://github.com/rock-gui/gui-robot_model/blob/master/test/CMakeLists.txt

No idea why it works on ubuntu though.

> in directory /data/jenkins/workspace/workspace/rock-complete/Flavor/master/node/Debian_testing/dev/gui/robot_model/build
    [ 72%] Built target robot_model-viz
    [ 81%] Generating moc_my_timer.cxx
    /bin/sh: 1: Qt4::moc: not found
    test/CMakeFiles/plugintest.dir/build.make:53: recipe for target 'test/moc_my_timer.cxx' failed

**Comment by maltewi** [comment]
Tested what you suggested with the build server (see http://buildsrv01:8080/job/rock-complete/928/Flavor=master,node=Debian_testing/consoleText). Seems to work.
